package com.alipay.rmall.dal.dao;

import com.alipay.rmall.dal.domain.ProductBaseInfoDO;
import com.alipay.rmall.dal.domain.ProductBaseInfoParam;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

/**
 * This class was generated by Ali-Generator
 * @author xurui
 */
@Mapper
public interface ProductBaseInfoDAO {
    /**
     * 根据WHERE条件COUNT
     * @param productBaseInfoParam
     * @return
     *
     * @mbg.generated
     */
    long countByParam(ProductBaseInfoParam productBaseInfoParam);

    /**
     * 根据WHERE条件删除
     * @param productBaseInfoParam
     * @return
     *
     * @mbg.generated
     */
    int deleteByParam(ProductBaseInfoParam productBaseInfoParam);

    /**
     * 根据主键删除
     * @param id
     * @return
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insert(ProductBaseInfoDO record);

    /**
     * 根据字段选择性插入单条记录
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int insertSelective(ProductBaseInfoDO record);

    /**
     * 根据WHERE条件查询，返回不包含长文本字段
     * @param productBaseInfoParam
     * @return
     *
     * @mbg.generated
     */
    List<ProductBaseInfoDO> selectByParam(ProductBaseInfoParam productBaseInfoParam);

    /**
     * 根据主键查询
     * @param id
     * @return
     *
     * @mbg.generated
     */
    ProductBaseInfoDO selectByPrimaryKey(Integer id);

    /**
     * 根据WHERE条件选择性更新
     * @param record
     * @param productBaseInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParamSelective(@Param("record") ProductBaseInfoDO record, @Param("productBaseInfoParam") ProductBaseInfoParam productBaseInfoParam);

    /**
     * 根据WHERE条件更新，不更新长文本字段
     * @param record
     * @param productBaseInfoParam
     * @return
     *
     * @mbg.generated
     */
    int updateByParam(@Param("record") ProductBaseInfoDO record, @Param("productBaseInfoParam") ProductBaseInfoParam productBaseInfoParam);

    /**
     * 根据主键选择性更新
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProductBaseInfoDO record);

    /**
     * 根据主键更新，不更新长文本字段
     * @param record
     * @return
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProductBaseInfoDO record);

    /**
     * 批量插入
     * @param records
     * @return
     *
     * @mbg.generated
     */
    int batchInsert(List<ProductBaseInfoDO> records);
}